#!/bin/sh

case "$1" in
	start)
		echo 0 > /sys/class/gpio/export
		echo out > /sys/class/gpio/gpio0/direction
		echo 0 > /sys/class/gpio/gpio0/value
		echo 1 > /sys/class/gpio/gpio0/value
		setprop sys.rgb.color.type 4
		colorLedSpi &

		;;
	stop)
		echo 0 > /sys/class/gpio/gpio0/value
		killall colorLedSpi
		;;
	restart|reload)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit 0
