#!/bin/sh
#
# Start wifi_daemon....
#

start() {
      printf "Starting wifi_daemon....: "
	  wifi_daemon
	  sleep 2
	  #wifi -o sta
	  #hostapd -B /etc/hostapd.conf
	  #ifconfig wlan0 192.168.5.1
	  #dnsmasq -C /etc/dnsmasq.conf -l /var/dnsmasq.leases -x /var/dnsmasq.pid
}

stop() {
	printf "Stopping wifi_daemon: "
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
